config/routes.rb
Rails.application.routes.draw do
  resources :indeed_results

  resources :searches
  post 'compare' => 'searches#compare'

  devise_for :users
  resources :pages

  root 'pages#index'
  get 'faq' => 'pages#faq'

end

app/models/indeed_result.rb
class IndeedResult < ActiveRecord::Base
  belongs_to :search

  validates :score, presence: true
  validates :job_total_1, presence: true
  validates :job_total_2, presence: true
  validates :job_listing_1, presence: true
  validates :job_listing_2, presence: true
  validates :job_raw_1, presence: true
  validates :job_raw_2, presence: true
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  belongs_to :search

  validates :score, presence: true, numericality: true
  validates :name, presence: true
  validates :total_members, presence: true, numericality: { only_integer: true }
  validates :total_meetups, presence: true, numericality: { only_integer: true }
  validates :avg_relevancy, presence: true, numericality: { only_integer: true }
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base

  belongs_to :user
  has_one :indeed_result, dependent: :destroy
  has_many :meetup, dependent: :destroy

  validates :job1, presence: true
  validates :job2, presence: true
  validates :location, presence: true
  validates :user_id, presence: true
  validates :job_scale, presence: true, :numericality => { :greater_than_or_equal_to => 10, :less_than_or_equal_to => 90 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :searches, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  # Override Devise default redirect path for sign in
  def after_sign_in_path_for(resouce)
    searches_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render :layout => 'home'
  end
  def faq
  end
end

app/controllers/searches_controller.rb
# Search Controller
class SearchesController < ApplicationController
  before_action :authenticate_user! # must be logged in
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  before_action :authorized_user, only: [:show, :edit, :update, :destroy] # must own page

  def index

    @search = current_user.searches
  end

  def new
    @search = current_user.searches.build
  end

  def create
    @search = current_user.searches.build(search_params)

    if @search.save

      # Call API lib
      indeed_service = IndeedService.new(Rails.application.secrets.indeed_api, request.env)
      indeed_service.execute(@search.job1, @search.job2, @search.job_scale, @search.location)
      @indeed = @search.create_indeed_result(indeed_service.response)

      # Meetup
      meetup_service = MeetupService.new(@search.meetup_interests, @search.location)
      meetup_service.execute
      @search.meetup.create(meetup_service.response) # save to has_many (batch insert)

      flash[:success] = 'New search created!'
      redirect_to searches_path
    else
      flash[:error] = 'Search had a problem saving to the database'
      render 'new'
    end
  end

  def show
    @indeed = IndeedResult.find_by(search_id: @search.id)
  end

  def edit
    render 'new'
  end

  def update

    indeed_service = IndeedService.new(Rails.application.secrets.indeed_api, request.env)
    indeed_service.execute(@search.job1, @search.job2, @search.job_scale, @search.location)
    @indeed = @search.build_indeed_result(indeed_service.response)

    if @search.update_attributes(search_params)
      if @indeed.update_attributes(indeed_service.response)
        flash[:success] = "Search updated"
        redirect_to @search
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def destroy
    @search.destroy
    flash[:success] = "Search deleted"
    redirect_to searches_path
  end

  # Compare up to three searches
  def compare
    #https://github.com/superjustin/zip-codes-for-rails
    @compare = Search.limit(3).find(params[:compare])
  end

  private

    def set_search
      @search = Search.find(params[:id])
    end

    def authorized_user
      @search = Search.find(params[:id])
      @user = User.find(@search.user_id)
      redirect_to(root_url) unless current_user?(@user)
    end

    def search_params
      params.require(:search).permit(:job1, :job2, :location, :job_scale, :user_id, :meetup_interests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/indeed_results_helper.rb
module IndeedResultsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    temp
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">CityFit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'New Search', new_search_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'List Searches', searches_path, :class => 'navbar-link' %></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CityFit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
    <% if flash[:success] %>
      <p class="alert alert-success"><%= flash[:success] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="alert alert-danger"><%= flash[:error] %></p>
    <% end %>

    <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CityFit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
    <% if flash[:success] %>
      <p class="alert alert-success"><%= flash[:success] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="alert alert-danger"><%= flash[:error] %></p>
    <% end %>
</div>
<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/faq.html.erb
<li>How is are the scores calculated?</li>
<li>Both job total are used to determine the best fit for an area. A single job that is above 50 will recieve 100 points. If a job total is below 10 then a handicap will be placed on the other job by an amount of 33%. This helps prevent a single job having many results while the other not having any while still achieveing a high ranking score.</li>

app/views/pages/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>CityFit. Find a city that fits you.</h1>
    <%= link_to 'Register', new_user_registration_path, :class => 'btn btn-primary btn-lg', :role => 'button' %>
    <%= link_to 'Login', new_user_session_path, :class => 'btn btn-primary btn-lg', :role => 'button' %>
  </div>
</div>

<div class="container">
  <div class="row">
    <h2>Powered by the best</h2>
  </div>
</div>

<div class="container-wrapper meetup-bg">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= image_tag 'APIs/indeed.png' %>
          <div class="caption">
            <h3>Jobs from Indeed</h3>
            <p>We utilize data from Indeed.com to determine locations that provide lots of job opportunities.</p>
            <p><%= link_to 'Learn more', faq_path, :class => 'btn btn-default', :role => 'button' %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-wrapper green">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3 float-right">
        <div class="thumbnail">
          <%= image_tag 'APIs/meetup.png' %>
          <div class="caption">
            <h3>Social life from Meetup</h3>
            <p>By looking for local meetups in your area we can show you cities that have a robust social life.</p>
            <p><%= link_to 'Learn more', faq_path, :class => 'btn btn-default', :role => 'button' %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-wrapper medium-blue">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= image_tag 'APIs/trulia.jpg' %>
          <div class="caption">
            <h3>Real Estate &amp; Neighborhood from Trulia</h3>
            <p>By looking for local meetups in your area we can show you cities that have a robust social life.</p>
            <p><%= link_to 'Learn more', faq_path, :class => 'btn btn-default', :role => 'button' %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container-wrapper green">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3 float-right">
        <div class="thumbnail">
          <%= image_tag 'APIs/greatschools.png' %>
          <div class="caption">
            <h3>Education from GreatSchools</h3>
            <p>By looking for local meetups in your area we can show you cities that have a robust social life.</p>
            <p><%= link_to 'Learn more', faq_path, :class => 'btn btn-default', :role => 'button' %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searches/_error.html.erb
<!-- Change @user to be dynamic variable -->
<% if @search.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@search.errors.count, "error") %>.
      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/searches/compare.html.erb
<h1>CityFit Compatibility Comparison</h1>
<div class="container">
    <div class="row">
        <% @compare.each do |search| %>
            <div class="col-sm-4">
                <h2><%= search.location %></h2>
                <h3><%= search.indeed_result.score %><small> / 100</small></h3>
                <meter value="<%= search.indeed_result.score %>" max="100" title="<%= search.indeed_result.score %>"></meter>
                <hr />
                <h4><%= search.job1 %></h4>
                <p><strong>Total:</strong> <%= search.indeed_result.job_total_1 %></p>
                <h4><%= search.job2 %></h4>
                <p><strong>Total:</strong> <%= search.indeed_result.job_total_2 %></p>

                <%= link_to 'show details', search_path(search.id) %>
            </div>
        <% end %>
    </div>
</div>

app/views/searches/index.html.erb
<% #link_to 'Request', search_results_path(:id => item.id), method: :get %>
<%= form_tag '/compare' do -%>
    <table>
        <tr>
            <th></th>
            <th>Job1</th>
            <th>Job2</th>
            <th>Location</th>
            <th>Indeed Score</th>
            <th>Meetup Score</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

            <% @search.each do |item| %>
                <tr>
                    <td><%= check_box_tag 'compare[]', item.id, false, id: "compare_#{item.id}" %></td>
                    <td><%= item.job1 %></td>
                    <td><%= item.job2 %></td>
                    <td><%= item.location %></td>
                    <td><%= item.indeed_result.score if defined?(item.indeed_result.score) %></td>
                    <td><% item.meetup.each do |meetup| %>
                        <%= "#{meetup.name}: #{meetup.score}" %>
                    <% end %></td>
                    <td><%= link_to 'Edit', edit_search_path(item) %></td>
                    <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
            <tr>
                <td><%= submit_tag "Compare", class: 'btn btn-primary' %></td>
            </tr>
    </table>
<% end -%>

app/views/searches/new.html.erb
<h1>Create a Compatibility Search</h1>

<%= render 'searches/error' %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @search do |f| %>

            <%= f.label :job1, "Job 1" %>
            <%= f.text_field :job1, class: 'form-control' %>

            <%= f.label :job2, "Job 2" %>
            <%= f.text_field :job2, class: 'form-control' %>

            <%= f.label :job_scale, "Job Importance Scale" %>
            <div class="job-scale">
                <span class="job-scale-left">Job 1</span>
                <span class="job-scale-right">Job 2</span>
                <%= f.range_field :job_scale, :in => 10..90, :step => '10' %>
            </div>

            <%= f.label :location, "Location" %>
            <%= f.text_field :location, class: 'form-control' %>

            <%= f.label :enable_meetup, "Toggle Meetup Interests" %>
            <%= check_box_tag(:enable_meetup) %>

            <div class="meetup-section">
                <%= f.label :meetup_interests, "Meetup" %>
                <%= f.text_field :meetup_interests, class: 'form-control' %>
            </div>


            <br />
            <%= f.submit "Create Search", :disable_with => 'Create Searching...', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/searches/result.html.erb
<!-- <% @parsed_result.each do |item| %>
    <% item.each do |value| %>
        <%= value %>
    <% end %>
<% end %> -->


<% result1 = Array.new %>
<% result2 = Array.new %>

<h2><%= @search.location %></h2>
<p><%= @parsed_result[:score] %>/100</p>
<progress value="<%= @parsed_result[:score] %>" max="100" title="<%= @parsed_result[:score] %>"></progress>
<hr />
<% @parsed_result[:raw1]['results'].each do |job| %>
    <% result1.push "<h4><a href='#{job['url']}'>#{job['jobtitle']}</a></h4><p><strong>#{job['company']}</strong>&nbsp;<small>#{job['formattedLocation']}</small></p>".html_safe %>
<% end %>
<% @parsed_result[:raw2]['results'].each do |job| %>
    <% result2.push "<h4><a href='#{job['url']}'>#{job['jobtitle']}</a></h4><p><strong>#{job['company']}</strong>&nbsp;<small>#{job['formattedLocation']}</small></p>".html_safe %>
<% end %>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3><%= @search.job1 %>&nbsp;<small>(<%= @parsed_result[:job1Total] %>)</small></h3>
            <% result1.each do |item| %>
                <%= item %>
            <% end %>
        </div>
        <div class="col-sm-6">
            <h3><%= @search.job2 %>&nbsp;<small>(<%= @parsed_result[:job2Total] %>)</small></h3>
            <% result2.each do |item| %>
                <%= item %>
            <% end %>
        </div>
    </div>
</div>

app/views/searches/show.html.erb
<%= @response %>
<h4>Score: <%= @indeed.score %></h4>
<p>
  <strong>Job 1:</strong>
  <%= @search.job1 %>
  <ul>
    <li>total: <%= @indeed.job_total_1 %></li>
    <li>listing: <%= @indeed.job_listing_1.html_safe %></li>
  </ul>
</p>
<p>
  <strong>Job 2:</strong>
  <%= @search.job2 %>
  <ul>
    <li>total: <%= @indeed.job_total_2 %></li>
    <li>listing: <%= @indeed.job_listing_2.html_safe %></li>
  </ul>
</p>